### ISSUE TITLE
Netrunner 1 block  no reward

### ISSUE THREAD

**Issue by pihapi** [DEROFDN/Engram#11]
![image](https://user-images.githubusercontent.com/22814636/223427250-72585826-a9ca-45b1-9d1a-87b6cf0a8417.png)

1 Block - no reward

1727916 - https://explorer.dero.io/block/1727916
![image](https://user-images.githubusercontent.com/22814636/223427676-409c4c0c-bf04-4ec6-903f-c45d354ea32a.png)

The wallet number is someone else's in the explorer.
this is a lie?

**Comment by Nelbert442** [comment]
The explorer shows the miner addr that mined the integrator miniblock (final block of 10 in that makes up a block). There are other explorers that show all miners etc. (e.g. https://derostats.io/block/1727916) If you received a reward (0.0615) then you received the miniblock reward. If you did not, it's possible that you did not submit the job in time and did not get the reward, as this is possible depending on which node you're mining to. Latency to node, to peers, etc. all taken into account when mining.

Also for reference, netrunner has been split out for future versions at https://github.com/DEROFDN/Netrunner and Engram will in the future be separated from that in order to have node + miner separate from wallet itself as far as binaries are concerned. Currently in Engram , netrunner will use half threads to mine while in the dedicated 'Netrunner' repo you can customize as-needed as well as run your own node (preferred) for maximum privacy.

**Comment by pihapi** [comment]
![image](https://user-images.githubusercontent.com/22814636/223465601-9df82675-c69f-4de2-8a88-6755d9bbff95.png)

Restarted wallet and miner. Blocks 0. History is empty. A block was found and it just disappeared? There are no rewards. Did it all go to someone else's wallet? Where did the information about the found block disappear?

**Comment by Nelbert442** [comment]
The block details within netrunner are in memory, so only relevant to the instance you're running. It resets when you restart the miner.

Again with reference to your reward , that would be related to my previous comment.

**Comment by pihapi** [comment]
the program writes to me "1 block found", but you write to me that this may not be true? how can I trust the program or you?

**Comment by pihapi** [comment]
as you can see in the statistics there is not a single reward, even for part of the block

**Comment by Nelbert442** [comment]
Trust what you wish I suppose. Based on the miner state, if it believes a miniblock is found it returns said results. Netrunner has some modification to better display miniblocks as they actually are returned I believe, but still relevant to data from the node to which your miner is connected.

https://github.com/DEROFDN/Engram/blob/main/netrunner.go#L370



> as you can see in the statistics there is not a single reward, even for part of the block

Understood, and see my previous replies as perhaps reasons why.

In https://github.com/DEROFDN/Netrunner we are pulling the miniblock counts from the job data itself which comes from the daemon which should more properly reflect accepted/rejected blocks closer to reality rather than just appending data output when you find a matching PoW which is then submitted. - https://github.com/DEROFDN/netrunner/blob/main/miner.go#L274

**Comment by pihapi** [comment]
https://derostats.io/block/1727916

me dero1qy4vdzs8qzz4qwggjvguesv44xz5z4ltyr0kf9hlg6229x3tuean6qq9pv34r

**Comment by Nelbert442** [comment]
> https://derostats.io/block/1727916
> 
> me dero1qy4vdzs8qzz4qwggjvguesv44xz5z4ltyr0kf9hlg6229x3tuean6qq9pv34r

Then you should have a reward. Be sure you're connected to a fully synced node.

**Comment by pihapi** [comment]
I'm saying there is nothing. It's been days, but there's nothing. From the moment the block was found, it did not restart or turn off. So the whole node is synchronized. And there's nothing

**Comment by Nelbert442** [comment]
> I'm saying there is nothing. It's been days, but there's nothing. From the moment the block was found, it did not restart or turn off. So the whole node is synchronized. And there's nothing

Understood. Only thing I could say is be sure that the address you have open within Engram is the address you linked above and verified w/ the block data. Not much more ideas I can provide there.

I do recommend  utilizing [Netrunner](https://github.com/DEROFDN/Netrunner) as a standalone app now for mining rather than within Engram, as in future updates they will be decoupled. Or you can utilize the standalone miner if you choose as well, up to you.

**Comment by pihapi** [comment]
There is no difference how to use it either separately or in a wallet. it is more important that everything works, and does not deceive. There is no reward. All this is a lie. I mined with other miners and as you can see everything came to the wallet, but for some reason Netrunner does not work and deceives me. How long does it take to get a reward or is Netrunner just mining on the developer's wallet and stealing from me?

**Comment by Nelbert442** [comment]
> There is no difference how to use it either separately or in a wallet. it is more important that everything works, and does not deceive. There is no reward. All this is a lie. I mined with other miners and as you can see everything came to the wallet, but for some reason Netrunner does not work and deceives me. How long does it take to get a reward or is Netrunner just mining on the developer's wallet and stealing from me?

If you read my replies you'll see why. But everyone can make their own opinions.

I'll re-quote the components that are relevant to why Engram's built-in netrunner can potentially report miniblocks found when they are not: 

Based on the miner state, if it believes a miniblock is found it returns said results. Netrunner has some modification to better display miniblocks as they actually are returned I believe, but still relevant to data from the node to which your miner is connected.

https://github.com/DEROFDN/Engram/blob/main/netrunner.go#L370

In https://github.com/DEROFDN/Netrunner we are pulling the miniblock counts from the job data itself which comes from the daemon which should more properly reflect accepted/rejected blocks closer to reality rather than just appending data output when you find a matching PoW which is then submitted. - https://github.com/DEROFDN/netrunner/blob/main/miner.go#L274

TL&DR: Engram's built-in miner will report miniblock found in the event your local miner finds a valid PoW that it intends to submit. It does NOT, however, know whether the submission goes through successfully or not so it simply ticks up the counter and moves on. Netrunner, as a separate entity, has some modifications to this procedure to which it pulls the accepted/rejected miniblock states that are mined directly from the daemon itself which will be the source of truth with respect to miniblocks sent through the respective daemon if they're allowed or rejected.

**Comment by pihapi** [comment]
![image](https://user-images.githubusercontent.com/22814636/223486196-84ca2a0c-b164-4172-8c23-b605013ab4f4.png)
![image](https://user-images.githubusercontent.com/22814636/223488397-9c87ff11-716e-4cf5-90f1-d515e6618cf5.png)


just in case

**Comment by Nelbert442** [comment]
> ![image](https://user-images.githubusercontent.com/22814636/223486196-84ca2a0c-b164-4172-8c23-b605013ab4f4.png) ![image](https://user-images.githubusercontent.com/22814636/223488397-9c87ff11-716e-4cf5-90f1-d515e6618cf5.png)
> 
> just in case

all good there. Just a point of clarification , I am not validating that the derostats data is correct, just more a point of reference. Let me see if I can pull the latest data, as I'm not sure their config on when they pull the miner data (in the e vent it gets reorganized etc a few blocks later).

**Comment by Nelbert442** [comment]
Looks like your address did mine the mbl:

Hash | "e7fb52ab065f1f1259c5cb5b4d37de0d3f9e4d8cd65ebb4e2a663d92282500d5"
Miner | "dero1qy4vdzs8qzz4qwggjvguesv44xz5z4ltyr0kf9hlg6229x3tuean6qq9pv34r"

If you want to be absolutely sure, can always restore seeds to https://github.com/deroproject/derohe/releases/latest ; extract and use dero-wallet and pass --remote.

While Engram should show the balance appropriately as well, it's also worth trying to at least verify with the cli wallet as well, it does seem like it should have come to you given a query against the daemon data. Anyways, just trying to provide avenues to test and validate

**Comment by Nelbert442** [comment]
Netrunner has been moved to its' own application and separated out from Engram itself. Please see https://github.com/DEROFDN/Netrunner

Please also see latest Engram build at https://github.com/DEROFDN/Engram/releases/latest
