### ISSUE TITLE
cant create a new account

### ISSUE THREAD

**Issue by ganesha108** [DEROFDN/Engram#8]
every time I tap the new account link Engram closes

**Comment by DankFC** [comment]
Engram is a portable app, so it needs to have write permissions in order to function. Make sure of the following:

1. The app was extracted before opening.
2. The app has write permissions where it is stored.
3. Check your settings to make sure it is connecting to a node, or running a node itself. You can click the 'restore defaults' button at the bottom of the setting screen and restart Engram to correct connection issues.

**Comment by Nelbert442** [comment]
Please download or build from latest release https://github.com/DEROFDN/Engram/releases/latest and feel free to re-open relevant issues should you still encounter them.
